### PR TITLE
Websocket test for large messages

### PR DESCRIPTION
**Pull request by jabbera**
Per the [following post](http://mediabrowser.tv/community/index.php?/topic/10137-vox-commando-integration/?p=145076) it appears that messages were being truncated by the websocket client or server. This pull adds unit tests for http[s] normal websocket communications and one large message test. The large message test passed out of the box. After investigation it turns out that downgrading from WebSocket4Net 0.11 to 0.10 causes the issue to occur. The api client was already upgraded to 0.11 in [this commit](https://github.com/MediaBrowser/MediaBrowser.ApiClient/commit/f765873d5acc8b83854598033775b1c7699c1d08) on 12-23. Assuming it's been released to nuget already this issue should be resolved. 

To reproduce the failure use the package manager console on the test project and run:

Install-Package WebSocket4Net -Version 0.10

comment out dispose in the test as thiswas not added till 0.11. You should see the test fail.

I assume [this is the commit](https://websocket4net.codeplex.com/SourceControl/changeset/f3ad1fbe97aab999dbd5853387fedf4158ec3d3b) that resolved the issue. I'm too lazy to bisect.

### CODE REVIEW

**Comment by LukePulverenti** [comment]
great stuff, thanks!

**Comment by jabbera** [comment]
No problem. I'll leave it to you to comment back to the poster on the forums.

**Comment by ebr11** [comment]
Yes, awesome.  Did you test this on a Windows 7 server?

**Comment by LukePulverenti** [comment]
It doesn't matter anymore. there's no more difference between win 7 and 8.

**Comment by jabbera** [comment]
Just for completeness I did. Windows 8 and I don't get along so well.

**Pull request merged**
